/*
 * list.c: List of pointers to puzzle structures, for monolithic
 * platforms.
 *
 * This file is automatically generated by mkfiles.pl. Do not edit
 * it directly, or the changes will be lost next time mkfiles.pl runs.
 * Instead, edit Recipe and/or its *.R subfiles.
 */
#include "puzzles.h"
#define GAMELIST(A) \
    A(abcd) \
    A(ascent) \
    A(blackbox) \
    A(boats) \
    A(bridges) \
    A(clusters) \
    A(crossing) \
    A(cube) \
    A(dominosa) \
    A(fifteen) \
    A(filling) \
    A(flip) \
    A(flood) \
    A(galaxies) \
    A(guess) \
    A(inertia) \
    A(keen) \
    A(lightup) \
    A(loopy) \
    A(magnets) \
    A(map) \
    A(mathrax) \
    A(mines) \
    A(net) \
    A(netslide) \
    A(palisade) \
    A(pattern) \
    A(pearl) \
    A(pegs) \
    A(range) \
    A(rect) \
    A(rome) \
    A(salad) \
    A(samegame) \
    A(seismic) \
    A(signpost) \
    A(singles) \
    A(sixteen) \
    A(slant) \
    A(solo) \
    A(spokes) \
    A(tents) \
    A(towers) \
    A(tracks) \
    A(twiddle) \
    A(undead) \
    A(unequal) \
    A(unruly) \
    A(untangle) \

#define DECL(x) extern const game x;
#define REF(x) &x,
GAMELIST(DECL)
const game *gamelist[] = { GAMELIST(REF) };
const int gamecount = lenof(gamelist);
